import type { MetadataRoute } from "next";

/**
 * What makes the phone treat this as an app rather than a bookmark: a name
 * for the icon, standalone display so Safari's chrome disappears and the
 * design fills the screen, and an ink background behind the launch.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Main Street Steakhouse League",
    short_name: "Steakhouse",
    description: "The Main Street Steakhouse League, est. 2016: Tonight's Table, live scoring, the draft room, the clubhouse, head-to-head bets and the Weekly Special. Private, twelve managers, no ads.",
    id: "/",
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#191614",
    theme_color: "#191614",
    categories: ["sports"],
    icons: [
      { src: "/icon.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icon.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
      { src: "/apple-icon.png", sizes: "180x180", type: "image/png" },
    ],
    // Two phone captures of the fixtures, so Android's install sheet shows the
    // app rather than a bare icon and a name. Regenerated by scripts/screenshots.mjs.
    screenshots: [
      { src: "/screenshots/tonight.png", sizes: "780x1688", type: "image/png", form_factor: "narrow", label: "Tonight's Table" },
      { src: "/screenshots/matchups.png", sizes: "780x1688", type: "image/png", form_factor: "narrow", label: "The Sunday board" },
    ],
    shortcuts: [
      { name: "Live scores", url: "/matchups", description: "This week's tables" },
      { name: "My team", url: "/team", description: "Set the lineup" },
    ],
  };
}
