"use client";

import { FormEvent, useCallback, useState } from "react";
import { Check, CircleDollarSign, LockKeyhole, Plus, Swords, X } from "lucide-react";
import { TopBar } from "@/components/Shell";
import { SkeletonRows } from "@/components/ui";
import { LEAGUE_ID } from "@/lib/config";
import { useLive } from "@/lib/live";
import { useSession } from "@/lib/session";
import { supabaseBrowser } from "@/lib/supabase/client";
import type { Challenge } from "@/lib/types";

export default function ChallengesPage(){
 const{ready,user,teams}=useSession();const[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
 const fetcher=useCallback(async()=>{const{data,error:readError}=await supabaseBrowser().from("challenges").select("*").eq("league_id",LEAGUE_ID).order("created_at",{ascending:false});if(readError)throw readError;return(data??[])as Challenge[]},[]);
 const{data,status,refetch}=useLive(fetcher,{tables:["challenges"],channel:"league-challenges",pollMs:30000,enabled:ready});
 const nameOf=(id:string)=>teams.find(team=>team.owner_id===id)?.name??"League manager";
 async function respond(id:string,response:"accepted"|"declined"){setBusy(true);setError(null);const{error:rpcError}=await supabaseBrowser().rpc("ff_respond_challenge",{p_challenge_id:id,p_response:response});setBusy(false);if(rpcError)return setError(rpcError.message);await refetch()}
 return <><TopBar status={status}/><main className="page" data-width="mid"><header style={{display:"flex",alignItems:"flex-end",justifyContent:"space-between",gap:"var(--s4)",marginBottom:"var(--s5)",flexWrap:"wrap"}}><div><div className="eyebrow" data-tone="gold">HEAD TO HEAD</div><h1 className="display" style={{fontSize:"var(--t-title)",margin:"var(--s2) 0"}}>Call your shot.</h1><p className="prose">Lock the terms, then let fantasy results settle the argument.</p></div><button className="btn" data-v="primary" onClick={()=>setOpen(true)}><Plus size={14}/>New challenge</button></header>
 <div className="card" data-accent="gold" style={{display:"flex",gap:"var(--s3)",padding:"var(--s4)",marginBottom:"var(--s4)"}}><LockKeyhole size={18} color="var(--gold)" style={{flexShrink:0}}/><p style={{margin:0,color:"var(--muted)",fontSize:"var(--t-small)"}}><strong style={{color:"var(--cream)"}}>Social challenge mode.</strong> The league records accepted terms and results. It does not custody funds or automatically debit personal Venmo accounts.</p></div>
 {error&&<p role="alert" style={{color:"var(--lose)"}}>{error}</p>}{!data?<div className="card"><SkeletonRows n={5}/></div>:<div className="grid-auto">{data.length===0&&<div className="card"><div className="empty">No challenges yet.<br/>Be the first to call your shot.</div></div>}{data.map(item=><article className="card" key={item.id} data-accent={item.status==="accepted"?"gold":undefined}><div className="card__head"><span className="badge">{item.status}</span><CircleDollarSign size={16} color="var(--gold)"/></div><div className="card__body"><div className="eyebrow">{nameOf(item.challenger_id)} vs {nameOf(item.opponent_id)}</div><h2 style={{fontFamily:"var(--serif)",margin:"var(--s2) 0"}}>{item.title}</h2><p style={{color:"var(--muted)",whiteSpace:"pre-wrap"}}>{item.terms}</p><div style={{display:"flex",justifyContent:"space-between",borderTop:"1px solid var(--rule)",paddingTop:"var(--s3)",marginTop:"var(--s4)"}}><span className="eyebrow">Stakes</span><strong>{item.stake_label}</strong></div>{item.status==="proposed"&&item.opponent_id===user?.id&&<div style={{display:"flex",gap:"var(--s2)",marginTop:"var(--s4)"}}><button className="btn" data-v="primary" disabled={busy} onClick={()=>void respond(item.id,"accepted")}><Check size={14}/>Accept & lock</button><button className="btn" disabled={busy} onClick={()=>void respond(item.id,"declined")}><X size={14}/>Decline</button></div>}</div></article>)}</div>}
 {open&&<ChallengeDialog close={()=>setOpen(false)} done={async()=>{setOpen(false);await refetch()}}/>}</main></>;
}
function ChallengeDialog({close,done}:{close:()=>void;done:()=>Promise<void>}){const{user,teams}=useSession();const[opponent,setOpponent]=useState(""),[title,setTitle]=useState(""),[terms,setTerms]=useState(""),[stake,setStake]=useState("Bragging rights"),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);const choices=teams.filter(team=>team.owner_id&&team.owner_id!==user?.id);async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError(null);const team=choices.find(item=>item.id===opponent);const{error:rpcError}=await supabaseBrowser().rpc("ff_create_challenge",{p_league_id:LEAGUE_ID,p_opponent_id:team?.owner_id,p_title:title,p_terms:terms,p_stake_label:stake,p_proposition_type:"custom"});setBusy(false);if(rpcError)return setError(rpcError.message);await done()}return <div className="modal" onMouseDown={e=>e.target===e.currentTarget&&close()}><section className="modal__panel"><div className="card__head"><div><div className="eyebrow" data-tone="gold">NEW CHALLENGE</div><h2 style={{fontFamily:"var(--serif)",margin:"var(--s1) 0"}}>Call your shot</h2></div><button className="btn" data-v="ghost" data-size="icon" onClick={close} aria-label="Close"><X/></button></div><form className="card__body" onSubmit={submit} style={{display:"grid",gap:"var(--s4)"}}><Field label="Opponent"><select className="field" required value={opponent} onChange={e=>setOpponent(e.target.value)}><option value="">Choose a manager</option>{choices.map(team=><option value={team.id} key={team.id}>{team.name}</option>)}</select></Field>{!choices.length&&<p style={{color:"var(--muted)",margin:0}}>Other managers must claim their teams first.</p>}<Field label="Title"><input className="field" required maxLength={90} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Higher Week 1 score"/></Field><Field label="Exact terms"><textarea className="field" required maxLength={1000} value={terms} onChange={e=>setTerms(e.target.value)} rows={4} placeholder="Winner has the higher final fantasy score…"/></Field><Field label="Stakes"><select className="field" value={stake} onChange={e=>setStake(e.target.value)}><option>Bragging rights</option><option>Winner&apos;s dinner</option><option>League punishment</option><option>Charitable pledge</option><option>Settle externally</option></select></Field>{error&&<p role="alert" style={{color:"var(--lose)",margin:0}}>{error}</p>}<button className="btn" data-v="primary" disabled={busy||!choices.length}><Swords size={14}/>{busy?"Sending…":"Send challenge"}</button></form></section></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span className="eyebrow" style={{display:"block",marginBottom:6}}>{label}</span>{children}</label>}
